# -*- coding: utf-8 -*-
"""cifar10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4uZMnbL3bxRqrkVX_blymoczAVgG6n4
"""

import tensorflow as tf
from tensorflow.keras import datasets,models,layers
import matplotlib.pyplot as plt
(train_images,train_labels),(test_images,test_labels)=datasets.cifar10.load_data()
train_images,test_images=train_images/255.0,test_images/255.0
class_names=["aeroplane",'automobile','bird','cat','deer','dog','frog','horse','ship','truck']
plt.figure(figsize=(10,10))
for i in range(25):
      plt.subplot(5,5,i+1)
      plt.xticks([])
      plt.yticks([])
      plt.grid(False)
      plt.imshow(train_images[i],cmap=plt.cm.binary)
      plt.xlabel(class_names[train_labels[i][0]])
      plt.show